function out = simulateClosedLoop(p, traj, controller, Ts, tEnd, x0)
%SIMULATECLOSEDLOOP Closed-loop simulation of the nonlinear quadrotor.
%   OUT = SIMULATECLOSEDLOOP(P, TRAJ, CONTROLLER, TS, TEND, X0) simulates
%   the nonlinear truth model (QUADROTORSTATEFCN) in closed loop with the
%   given CONTROLLER, tracking the reference generated by
%   CIRCLETRAJECTORY(t, P, TRAJ) from t=0 to t=TEND.
%
%   CONTROLLER is a struct with fields:
%       .type   - 'LQR' or 'NMPC'
%       .K      - (LQR) state-feedback gain, 4x12
%       .nlobj  - (NMPC) nlmpc object
%
%   TS is the controller sample time (s); the plant is integrated with
%   RK4 using NSUB sub-steps per control interval for better accuracy
%   than the controller's own discretization.
%
%   OUT fields: t, X (12xN), U (4xN), Ref (12xN), uCompTime (1xN, NMPC
%   solve time per step, NaN for LQR).

nSub = 10;
dtSim = Ts / nSub;
N = round(tEnd / Ts);

X = zeros(12, N+1);
U = zeros(4, N);
Ref = zeros(12, N+1);
uCompTime = nan(1, N);

X(:,1) = x0;
r0 = circleTrajectory(0, p, traj);
Ref(:,1) = r0.state;

lastMV = p.uHover * ones(4,1);

isMPC = strcmpi(controller.type, 'MPC');
isNMPC = strcmpi(controller.type, 'NMPC');
if isNMPC
    Hp = controller.nlobj.PredictionHorizon;
elseif isMPC
    mpcObj = controller.mpcObj;
end

for k = 1:N
    tk = (k-1) * Ts;
    rk = circleTrajectory(tk, p, traj);
    Ref(:,k) = rk.state;
    xk = X(:,k);

    if isMPC
        tic;
        [uk] = mpcmove(mpcObj, xk, rk.state(1:12));
        uCompTime(k) = toc;
    elseif isNMPC
        tPreview = tk + Ts*(1:Hp);
        refPreview = circleTrajectory(tPreview, p, traj);
        refPreviewPos = refPreview.state(1:6, :);  % Extract [x y z phi theta psi]
        Yref = refPreviewPos';   % Hp x 6
        tic;
        [uk, ~, info] = nlmpcmove(controller.nlobj, xk, lastMV, Yref);
        uCompTime(k) = toc;
        if ~info.ExitFlag
            warning('simulateClosedLoop:NMPCInfeasible', ...
                'NMPC solve flagged non-optimal exit at t=%.3f s (ExitFlag=%d)', tk, info.ExitFlag);
        end
    else
        uk = p.uHover*ones(4,1) - controller.K * (xk - rk.state);
    end

    uk = min(max(uk, p.uMin), p.uMax);
    U(:,k) = uk;
    lastMV = uk;

    xsub = xk;
    for s = 1:nSub
        xsub = rk4Step(@(x) QuadrotorStateFcn(x, uk), xsub, dtSim);
    end
    X(:,k+1) = xsub;

    rk1 = circleTrajectory(k*Ts, p, traj);
    Ref(:,k+1) = rk1.state;
end

out.t = (0:N) * Ts;
out.X = X;
out.U = U;
out.Ref = Ref;
out.uCompTime = uCompTime;

end

% ------------------------------------------------------------------
function xNext = rk4Step(f, x, dt)
k1 = f(x);
k2 = f(x + dt/2*k1);
k3 = f(x + dt/2*k2);
k4 = f(x + dt*k3);
xNext = x + dt/6*(k1 + 2*k2 + 2*k3 + k4);
end
